### ISSUE TITLE
Home 페이지 UI 수정 / 추가

### ISSUE THREAD

**Issue by Jisu0528** [StudyBuddyCorps/Front-end#45]
## Description

> Home 페이지 UI 수정과 추가를 한다.

## Todo
- [x] 스터디룸 버튼 url 일치하도록 수정
- [x] 전체적인 간격 수정
- [x] 프로필 버튼 관련 ui 추가 (#53)
